language: node_js
node_js:
  - 12

script:
  - eslint 'src/**'
  - zip -r elobrain.zip dist .env package.json package-lock.json

deploy: 
  provider: elasticbeanstalk
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: $AWS_SECRET_KEY
  region: us-east-2
  app: nodejs-elobrain
  env: nodejs-elobrain
  bucket_name: nodejs-elobrain
  zip_file: elobrain.zip
  verbose: true
  skip_cleanup: true